generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  gains:
    arm_joint_1:
      p: 200
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_2:
      p: 200
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_3:
      p: 200
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_4:
      p: 200
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_5:
      p: 200
      d: 1
      i: 1
      i_clamp: 1
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
